projeto_financas_pessoais/financial_account/urls.py
from django.urls import path

from . import views

app_name = 'financial_accounts'

urlpatterns = [
    path('new/', views.new, name='new')
]

projeto_financas_pessoais/personal_finances/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('financial-accounts/', include('financial_account.urls')),
    path('transactions/', include('transactions.urls'))

    # path('registration/', RedirectView.as_view(url='login/', permanent=True))
]

projeto_financas_pessoais/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('me/', views.detail, name='detail'),
    path('me/financial-accounts/', views.list_accounts, name='list_accounts'),
    path('me/financial-account/<int:account_id>', views.account_detail, name='account_detail'),
    path('me/transactions/', views.list_transactions, name='list_transactions')
]

projeto_financas_pessoais/financial_account/models.py
from django.db import models

from users.models import User


class FinancialAccount(models.Model):
    name = models.CharField(max_length=100)
    balance = models.FloatField(default=0)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tb_financial_accounts'

projeto_financas_pessoais/users/models.py
from django.db import models
from django.contrib.auth.models import User as AuthUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AuthUser):

    class Meta(AuthUser.Meta):
        db_table = 'tb_users'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        db_table = 'tb_profiles'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

projeto_financas_pessoais/financial_account/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import FinancialAccount


def new(request):

    if request.method == 'GET':
        return render(request, 'financial_accounts/new.html')

    elif request.method == 'POST':

        name = request.POST.get('name')
        balance = request.POST.get('balance')

        # Substituímos a vírgula por ponto, caso exista
        balance = balance.replace(',', '.')

        # Tiramos os espaços em branco restantes, se houverem
        balance = balance.strip().replace(' ', '')

        if not len(balance):
            financial_account = FinancialAccount(name=name)
        else:
            financial_account = FinancialAccount(name=name, balance=float(balance))

        financial_account.user = request.user.user
        financial_account.save()

        return HttpResponseRedirect(reverse('users:index',))

projeto_financas_pessoais/users/views.py
from django.db.models import Q
from django.shortcuts import render

from financial_account.models import FinancialAccount
from transactions.models import Transactions


def index(request):

    user = request.user.user

    context = {
        # Pega todas as contas relacionadas ao usuário atualmente logado
        'financial_accounts': user.financialaccount_set.all(),

        # Pegue todas as transações onde o atributo debit_account (que é uma chave estrangeira para a
        # model FinancialAccount tenha o seu atributo user igual ao usuário atualmente logado.
        # Ou seja, pega todas as transações no banco que contém contas que sejam do usuário logado
        'transactions': Transactions.objects.filter(debit_account__user=user).all()
    }

    return render(request, 'users/index.html', context=context)


def detail(request):
    return render(request, 'users/detail.html')


def list_accounts(request):

    user = request.user.user

    context = {
        'financial_accounts': user.financialaccount_set.all()
    }

    return render(request, 'financial_accounts/list_user_accounts.html', context=context)


def list_transactions(request):

    user = request.user.user

    context = {
        'transactions': Transactions.objects.filter(debit_account__user=user).all()
    }

    return render(request, 'transactions/list_user_transactions.html', context=context)


def account_detail(request, account_id):

    account = FinancialAccount.objects.get(pk=account_id)
    account_transactions = Transactions.objects.filter(
        Q(debit_account=account) | Q(credit_account=account)
    ).order_by('-timestamp')

    context = {
        'account': account,
        'account_transactions': account_transactions
    }

    return render(request, 'financial_accounts/user_account_detail.html', context=context)

projeto_financas_pessoais/users/templates/financial_accounts/list_user_accounts.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col text-center">
            <h2>Lista de contas do usuário {{ user.first_name }}</h2>
            <h4><a href="{% url 'users:index' %}">Voltar a página principal</a></h4>
            <hr>
        </div>
    </div>
    <div class="row border-bottom border-dark">
        <div class="col">Nome da Conta</div>
        <div class="col">Saldo</div>
    </div>
    {% for financial_account in financial_accounts %}
        <div class="row my-1{% if forloop.counter0|divisibleby:'2' %} bg-secondary bg-opacity-10{% endif %}">
            <div class="col"><a href="{% url 'users:account_detail' financial_account.id %}">{{ financial_account.name }}</a></div>
            <div class="col">{{ financial_account.balance }}</div>
        </div>
    {% endfor %}
    <div class="row">
        <div class="col">
            <a href="{% url 'financial_accounts:new' %}">Criar uma nova conta</a>
        </div>
    </div>
</div>

{% endblock %}

projeto_financas_pessoais/users/templates/financial_accounts/user_account_detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row my-3">
        <div class="col text-center">
            <h1>Informações da conta '{{ account.name }}'</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h3>Data de criação: {{ account.created_at|date:"H:i:s d/m/Y" }}</h3>
        </div>
    </div>
    <div class="row border-bottom mb-3">
        <div class="col">
            <h3>Saldo atual: {{ account.balance }}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h2>Transações onde a conta '{{ account.name }}' aparece:</h2>
        </div>
    </div>
    {% if account_transactions %}
        <div class="row my-3 border-bottom">
            <div class="col"><strong>Conta Debitada</strong></div>
            <div class="col"><strong>Conta Creditada</strong></div>
            <div class="col"><stron>Valor</stron></div>
            <div class="col"><strong>Data/Hora</strong></div>
        </div>

        {% for transaction in account_transactions %}
            <div class="row">
                <div class="col">{{ transaction.debit_account.name }}</div>
                <div class="col">{{ transaction.credit_account.name }}</div>
                <div class="col">{{ transaction.value }}</div>
                <div class="col">{{ transaction.timestamp|date:"H:i:s d/m/Y" }}</div>
            </div>
        {% endfor %}

    {% else %}
        <div class="row">
            <div class="col">
                Essa conta não está associada a nenhuma transação.
            </div>
        </div>
    {% endif %}

    <div class="row my-3 border-top">
        <div class="col">
            <a href="{% url 'users:list_accounts' %}">Voltar para a listagem de contas</a>
        </div>
    </div>
</div>

{% endblock %}