projeto_financas_pessoais/financial_account/urls.py
from django.urls import path

from . import views

app_name = 'financial_accounts'

urlpatterns = [
    path('new/', views.new, name='new')
]

projeto_financas_pessoais/personal_finances/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('financial-accounts/', include('financial_account.urls')),
    path('transactions/', include('transactions.urls'))

    # path('registration/', RedirectView.as_view(url='login/', permanent=True))
]

projeto_financas_pessoais/transactions/urls.py
from django.urls import path

from . import views

app_name = 'transactions'

urlpatterns = [
    path('new/', views.new, name='new')
]

projeto_financas_pessoais/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('me/', views.detail, name='detail'),
    path('me/financial-accounts/', views.list_accounts, name='list_accounts'),
    path('me/financial-account/<int:account_id>', views.account_detail, name='account_detail'),
    path('me/transactions/', views.list_transactions, name='list_transactions')
]

projeto_financas_pessoais/users/models.py
from django.db import models
from django.contrib.auth.models import User as AuthUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AuthUser):

    class Meta(AuthUser.Meta):
        db_table = 'tb_users'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        db_table = 'tb_profiles'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

projeto_financas_pessoais/users/views.py
from django.db.models import Q
from django.shortcuts import render

from financial_account.models import FinancialAccount
from transactions.models import Transactions


def index(request):

    user = request.user.user

    context = {
        # Pega todas as contas relacionadas ao usuário atualmente logado
        'financial_accounts': user.financialaccount_set.all(),

        # Pegue todas as transações onde o atributo debit_account (que é uma chave estrangeira para a
        # model FinancialAccount tenha o seu atributo user igual ao usuário atualmente logado.
        # Ou seja, pega todas as transações no banco que contém contas que sejam do usuário logado
        'transactions': Transactions.objects.filter(debit_account__user=user).all()
    }

    return render(request, 'users/index.html', context=context)


def detail(request):
    return render(request, 'users/detail.html')


def list_accounts(request):

    user = request.user.user

    context = {
        'financial_accounts': user.financialaccount_set.all()
    }

    return render(request, 'financial_accounts/list_user_accounts.html', context=context)


def list_transactions(request):

    user = request.user.user

    context = {
        'transactions': Transactions.objects.filter(debit_account__user=user).all()
    }

    return render(request, 'transactions/list_user_transactions.html', context=context)


def account_detail(request, account_id):

    account = FinancialAccount.objects.get(pk=account_id)
    account_transactions = Transactions.objects.filter(
        Q(debit_account=account) | Q(credit_account=account)
    ).order_by('-timestamp')

    context = {
        'account': account,
        'account_transactions': account_transactions
    }

    return render(request, 'financial_accounts/user_account_detail.html', context=context)

projeto_financas_pessoais/users/templates/users/detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row my-3">
        <div class="col text-center">
            <h1>Perfil do usuário {{ user.username }}</h1>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <p><strong>Nome:</strong> {{ user.first_name }} {{ user.last_name }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p><strong>Email: </strong>{{ user.email }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p><strong>Data de Nascimento: </strong>{{ user.birth_date|date:"d/m/Y" }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p><strong>Data de Cadastro: </strong>{{ user.date_joined|date:"H:i:s d/m/Y" }}</p>
        </div>
    </div>
    <div class="row border-bottom">
        <div class="col">
            <p><strong>Data de último Login: </strong>{{ user.last_login|date:"H:i:s d/m/Y" }}</p>
        </div>
    </div>
    <div class="row my-2">
        <div class="col">
            <a href="{% url 'users:index' %}">Voltar para a página principal</a>
        </div>
    </div>

</div>

{% endblock %}

projeto_financas_pessoais/users/templates/users/index.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="max-width: 800px  ">
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col text-center">
                <h1>Sistema de Finanças Pessoais</h1>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'users:detail' %}">Perfil</a>
                        <a href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
                <hr>
            </div>
        </div>
    <div class="row">
        <div class="col text-center">
            {% if financial_accounts %}
                <h4>Você tem atualmente <a href="{% url 'users:list_accounts' %}">{{ financial_accounts|length }} contas</a> cadastradas</h4>
            {% else %}
                <h4>Você não possui contas cadastradas. <a href="{% url 'financial_accounts:new' %}">Cadastre a primeira</a></h4>
            {% endif %}
        </div>
    </div>
    <div>
         <div class="col text-center">
            {% if transactions %}
                <h4>Você tem atualmente <a href="{% url 'users:list_transactions' %}">{{ transactions|length }} transações</a> registradas</h4>
            {% else %}
                <h4>Você não possui transações registradas. <a href="{% url 'transactions:new' %}">Cadastre a primeira</a></h4>
            {% endif %}
        </div>
    </div>
    {% else %}
        <div class="row">
            <div class="col justify-content-center">
                Você precisa estar logado para acessar essa página. <a href="{% url 'login' %}">Fazer login</a>
            </div>
        </div>
    {% endif %}
</div>


{% endblock %}